# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wtz9vLp24jehxwZho5qdjaN5s2l5MPAN
"""

import pandas as pd
import numpy as np
import sqlite3

np.random.seed(101)
n_linhas = 800

dados_cx = {
    'ID_Feedback': range(5001, 5001 + n_linhas),
    'Canal_Atendimento': np.random.choice(['Chat', 'E-mail', 'Telefone', 'Autoatendimento'], n_linhas, p=[0.4, 0.2, 0.1, 0.3]),
    'Nota_NPS': np.random.choice([10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0], n_linhas, p=[0.3, 0.2, 0.15, 0.1, 0.05, 0.05, 0.03, 0.03, 0.03, 0.03, 0.03]),
    'Categoria_Feedback': np.random.choice(['Logística/Entrega', 'Qualidade do Produto', 'Atendimento ao Cliente', 'Navegação do App/Site', 'Preço/Pagamento'], n_linhas, p=[0.35, 0.20, 0.15, 0.20, 0.10]),
    'Comentario_Cliente': np.random.choice([
        'Entrega rápida e produto excelente',
        'Não gostei do atendimento pelo chat, demorado',
        'Produto veio com defeito e a troca foi difícil',
        'O aplicativo travou na hora de fechar a compra',
        'Preço justo e prazo cumprido',
        'Atrasou 3 dias e a caixa veio amassada',
        'Não consegui rastrear meu pedido pelo site',
        'Falta de informações técnicas na descrição'
    ], n_linhas)
}

df_cx = pd.DataFrame(dados_cx)

def classificar_nps(nota):
    if nota >= 9:
        return 'Promotor'
    elif nota >= 7:
        return 'Neutro'
    else:
        return 'Detrator'

df_cx['Classificacao_NPS'] = df_cx['Nota_NPS'].apply(classificar_nps)

df_cx.to_csv('feedback_clientes_cx.csv', index=False)

conn = sqlite3.connect('cx_analytics.db')
df_cx.to_sql('feedbacks', conn, if_exists='replace', index=False)
conn.close()